### ISSUE TITLE
Mill Max compatible?

### ISSUE THREAD

**Issue by deveth0** [imchipwood/dumbpad#16]
Hey, thank you so much for the board layouts!
I plan to build a "hotswap" able version, do you know by any chance, if the board i compatible to Mill Max sockets? 

Cheers

**Comment by imchipwood** [comment]
Never heard of them - unless they have the same pin locations as a cherry
MX switch, they won't be compatible.

**Comment by deveth0** [comment]
oh wow, that's fast, thanks! 
Mill max are just soldered into the wholes and provide some kind of hotswap for all kind of switches:
https://keygem.store/products/mill-max-hot-swap-sockets?_pos=1&_sid=fd8fb5200&_ss=r

**Comment by imchipwood** [comment]
Hmm, looks like it should work. I can't remember exactly but the holes should be the standard 0.060" (1.524mm). [This page](https://www.mill-max.com/search/tags/hot--swap-socket?keyword=keyboard%20switch%20socket&creative=&msclkid=4cba2cd1ad3f1726e10f4d25bdd1b5a5) shows the sleeve outer diameter at just under that (0.058" (1.47mm)), so they should squeeze in there.

Let me know if you try it out - I'm not much of a hot swapper but I've never seen these before and am curious how well they hold onto a switch!

**Comment by deveth0** [comment]
Sure, I'll keep you posted! I'd love to be able also use the dumbpad as kind of switch tester, so hot swap is a plus

**Comment by deveth0** [comment]
Sorry, can't provide feedback here as I did not order your PCB  :(
