### ISSUE TITLE
VIA Issue, no device detected.

### ISSUE THREAD

**Issue by Pushingboii** [imchipwood/dumbpad#18]
i'm a newb, got my dumbpad flashed by my friend. It works, but i cant change the layout from via configurator. I'm using v1.1 pcb. 
Thanks, and sorry for my broken english.

**Comment by imchipwood** [comment]
dumbpad is not currently supported in VIA.

@jfescobar18 [completed a PR in qmk_firmware](https://github.com/qmk/qmk_firmware/pull/13512) to add VIA support but it was reverted due to issues. I haven't looked into this since I don't use VIA... 

Sorry :/

**Comment by Pushingboii** [comment]
Okay then, thanks for your information, my friend said i have to use Vial app to change the layout.
Support from Indonesia....
And again, sorry for my broken english.
