### ISSUE TITLE
Not An Issue - I Designed Some 3D Printable Cases if you are interested

### ISSUE THREAD

**Issue by revere521** [imchipwood/dumbpad#2]
I designed these if you are interested - nice work by the way - the PCB's are great - I've had some fun with this

https://www.thingiverse.com/thing:4175635

**Comment by imchipwood** [comment]
Wow, sorry I missed this! Not sure why I didn't get notified of the issue - will look into that...

These are super cool - I like that you wired the rotary encoder as an external component for use with that huge knob!

Do you mind if I the thingiverse link to the READMEs?

**Comment by revere521** [comment]
I do not mind at all, please do!

I did make a smaller case too with the encoder on the board, but with the board still upside down.  The STEP files are there so it can be modified as a starting point fo rother configurations
