### ISSUE TITLE
OLED

### ISSUE THREAD

**Issue by itzzluk4s** [imchipwood/dumbpad#25]
hey, so i just bought the dumbpad with oled but i cant find any code for the firmware of it.

**Comment by imchipwood** [comment]
It's not merged into master

https://github.com/qmk/qmk_firmware/pull/17058

**Comment by itzzluk4s** [comment]
thanks for the help, are there any docs/tutorial on how to use this oled function

**Comment by imchipwood** [comment]
paging @medoix - I've never made one of the OLED boards so I don't know how they work.

**Comment by medoix** [comment]
@itzzluk4s the Dumbpad OLED hex firmware can be found here https://docs.keebd.com/firmware/

It is on my list to finish getting the PRs merged.
