### ISSUE TITLE
hi, i had an issue on the encoder and the third led

### ISSUE THREAD

**Issue by ryandiwdjj** [imchipwood/dumbpad#3]
the default mapping on qmk_firmware, the rotary and the third LED doesn't work (im using the v1.1 board) but i already make the fix and if you want i can send my files. (sorry for my bad english as it is not my mother language)

**Comment by imchipwood** [comment]
What branch did you use to build the qmk_firmware? The correct branch is `dumbpad_refactor` - maybe I forgot to push some code?

**Comment by ryandiwdjj** [comment]
i dont see any branch named dumbpad_refactor

**Comment by imchipwood** [comment]
OK, I see. You're talking about this repo and the Eagle files.

No update is needed in this repository if you use the correct qmk_firmware branch.

I am using a v1.1 right now and it's working fine with the code in [imchipwood/qmk_firmware/tree/dumbpad_refactor](http://github.com/imchipwood/qmk_firmware/tree/dumbpad_refactor)

**Comment by imchipwood** [comment]
The reason for this: v1.1 is significantly different from v1.0, in order to support both single- and dual-encoder layouts. The v1.1 layout uses the same encoder & LED pins as v0.6_dualencoder - the v1.1 design is actually based around the original dualencoder designs.

**Comment by ryandiwdjj** [comment]
aahh i see, anyway i have already fix it by myself after i trace it one by one LOL, i just though maybe someone out there had the same issue as me, thanks for the reply though! the design sure is beautiful!

**Comment by imchipwood** [comment]
Glad you like it, do you mind sending me a photo of yours? I like seeing what people have made :)

**Comment by ryandiwdjj** [comment]
here's mine, i use the third LED as my third layer indicator lmao, also forgive me as i'm not using the pcb mount switch, so it looks like a little bit misalign.

https://imgur.com/1YVRIGx

**Comment by imchipwood** [comment]
Awesome, I hadn't seen anyone put the encoders in opposite corners like that yet! 

Thanks for the photo - do you mind if I include it in the v1.1 README?

**Comment by ryandiwdjj** [comment]
yea i don't mind, hahahaha i think its kinda weird too but that is the most comfortable layout for me, also i'm going to try to make the acrylic case for it in free time, when its done i'm going to put the file in this issue

**Comment by imchipwood** [comment]
I'd actually like to close this issue - feel free to submit another issue when you've made the case!
