### ISSUE TITLE
Rotary encoder

### ISSUE THREAD

**Issue by Hintaa** [imchipwood/dumbpad#32]
I'm confused on how to program my rotary encoder to be vol up and down and when pressed media stop I was wondering if you could send me a .json file with the said features so i can use it

**Comment by TimoWielink** [comment]
What setup are you using (placement of the encoder) and what Arduino? I can send you a Binary file or help you setup QMK config.

**Comment by imchipwood** [comment]
Closing due to lack of response. Please open new issue if you still have troubles with the encorder.

**Comment by Hintaa** [comment]
The rotary encoder is on the bottom left and the rest is all switches
sorry for the late reply
