### ISSUE TITLE
Dumbpad issue...switches not working

### ISSUE THREAD

**Issue by tarnis** [imchipwood/dumbpad#36]
Hi, building a second dumbpad tonight, the column next to the rotory encoder slot and led's isn't working.  What is that linked to?

Great job on this board design btw!

**Comment by imchipwood** [comment]
Which version did you build?
-Chip

**Comment by tarnis** [comment]
Promicro

**Comment by imchipwood** [comment]
They all use a pro micro... Rgb? Oled? No LEDs?

**Comment by tarnis** [comment]
Lol...just the 3 LEDs above the rotary encoder.  Not a fancy one.  Combo I guess.  😁. Made these a long time ago.

**Comment by imchipwood** [comment]
Column 1 is pin D6 on the Pro Micro

Columns are numbered 0-4 from left to right, rows are 0-3 from top to bottom
[image: image.png]
-Chip

**Comment by imchipwood** [comment]
Image failed to send via email...
![image](https://github.com/imchipwood/dumbpad/assets/1298169/3567cb90-0017-4965-96fd-1391835ca4f4)

**Comment by tarnis** [comment]
That did the trick, appreciate your help!  Wish these worked with the hot swap sockets I bought....case looks like a trainwreck now 😞
