### ISSUE TITLE
Led 16 not working on dumbpad v3 hotswap

### ISSUE THREAD

**Issue by danlniel** [imchipwood/dumbpad#38]
So i just built my first dumbpad, but the last LED (LED 16) didn't work. I have already checked with a multimeter and changed the LED, any idea why?

**Comment by imchipwood** [comment]
What did you check with a multimeter? You can really only check that the signals are _connected_ properly, but a DMM isn't very useful to see what signals the LED is receiving. 

I didn't design that board so I don't have a whole lot of advice regarding it - the LEDs are all wired in sequence so if you have 15 working LEDs and one broken one, it's likely the LED is actually dead, or the pads that it attaches to are damaged.

**Comment by danlniel** [comment]
> You can really only check that the signals are connected properly

Yes i only check to make sure the signals are sent and received well

> but a DMM isn't very useful to see what signals the LED

I see

So far i dont think the LED is broken, i have a lot spare of LED and all are not working, most likely then the pads were damaged when I soldered. Thanks for help me investigate this problem, i will recheck again the board soon and in the meantime i think i will order a new board.
