### ISSUE TITLE
Flash mode

### ISSUE THREAD

**Issue by shaye1444** [imchipwood/dumbpad#4]
How would one go into flash mode to change firmware?

**Comment by breakawayt** [comment]
> How would one go into flash mode to change firmware?

Two methods that i've discovered:
1. Double-press the switch button (top of rotary encoder, if you've got this soldered)
2. Hold down rotary encoder pushbutton while plugging in to enter bootloader (according to config.h)
![image](https://user-images.githubusercontent.com/22266690/103436739-06d01580-4c5a-11eb-8998-e0be193c89e8.png)

**Comment by imchipwood** [comment]
If you're simply looking to flash, you only have to press the reset button once. This resets the Arduino and will temporarily enter the bootloader during the normal boot sequence - if your computer is currently attempting to flash the board, it will detect this and flashing will begin. Double pressing the reset button will enter the bootloader for 8 seconds.

These methods will work if you've already flashed the Arduino with QMK once:
* add `RESET` keycode to your keymap - this will also force it to enter the bootloader for 8 seconds
* hold down rotary encoder button while plugging in USB cable (or hit reset button once) to enter bootloader
