### ISSUE TITLE
Led question from a newbie 

### ISSUE THREAD

**Issue by cgdsyldrm** [imchipwood/dumbpad#40]
Hello, first and foremost thank you for sharing this beautiful macropad. I tried to find my answer another other issues but I couldn't.

So I am a new to this, both building a custom macropads and soldering but I'm getting there. Is it possible to add those circular led as in the photos? If so, do I need to solder them with a resistor or something? Also do I need to do something with the code?

![1695988325281](https://github.com/imchipwood/dumbpad/assets/14130514/661e1c64-fa38-4501-9801-aba4fd614d30)
![1695988325287](https://github.com/imchipwood/dumbpad/assets/14130514/3f2218fd-43c0-44d5-bae8-be7528539392)

**Comment by imchipwood** [comment]
I can't tell which board you're using but none of the boards are set up to use thru-hole LEDs in that way - the routing is very difficult on 2-layer PCBs, and since there's an RGB LED version available, I've never bothered to attempt the routing.

**Comment by cgdsyldrm** [comment]
Hello @imchipwood, the board is oled version, I see and thank you for the clarification.
