### ISSUE TITLE
3mm led orientation.

### ISSUE THREAD

**Issue by Sagzster** [imchipwood/dumbpad#42]
I was wondering what the orientation of the 3 possible 3mm led's are? anode towards rotary encoder or the Arduino?  Its not indicated on the PCB.

Thanks!
Brad

**Comment by imchipwood** [comment]
The cathode is towards the encoder - you can see tiny tabs from the solder
pad connecting it to the ground plane.

**Comment by Sagzster** [comment]
Thank You!
