### ISSUE TITLE
incorrect QMK link 

### ISSUE THREAD

**Issue by mike239x** [imchipwood/dumbpad#6]
Hi, I noticed in the main README the link to QMK is https://www.qmk.fm/
However, one can't properly reach that address, and the right one is https://qmk.fm/
Would be nice to fix that eventually :)

**Comment by imchipwood** [comment]
Oops! I have some other minor tweaks I want to make soon - will fix this as well.

**Comment by imchipwood** [comment]
Links fixed on master branch - thank you for pointing it out!
